package com.boge.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.boge.entity.LocalAndRecomendBook;

import com.boge.dao.LocalAndRecomendBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localAndRecomendBookDaoConfig;

    private final LocalAndRecomendBookDao localAndRecomendBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localAndRecomendBookDaoConfig = daoConfigMap.get(LocalAndRecomendBookDao.class).clone();
        localAndRecomendBookDaoConfig.initIdentityScope(type);

        localAndRecomendBookDao = new LocalAndRecomendBookDao(localAndRecomendBookDaoConfig, this);

        registerDao(LocalAndRecomendBook.class, localAndRecomendBookDao);
    }
    
    public void clear() {
        localAndRecomendBookDaoConfig.clearIdentityScope();
    }

    public LocalAndRecomendBookDao getLocalAndRecomendBookDao() {
        return localAndRecomendBookDao;
    }

}
