package com.boge.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOCAL_AND_RECOMEND_BOOK".
 */
@Entity
public class LocalAndRecomendBook {

    @Id
    private Long id;
    private String Path;
    private Long size;
    private String bookId;
    private String cover;

    @NotNull
    private String title;
    private String lastChapter;
    private Boolean isLocal;
    private Boolean hasUp;
    private Boolean isTop;

    private boolean isSelect = false;
    private int chaptersCount;

    @Generated
    public LocalAndRecomendBook() {
    }

    public LocalAndRecomendBook(Long id) {
        this.id = id;
    }

    @Generated
    public LocalAndRecomendBook(Long id, String Path, Long size, String bookId, String cover, String title, String lastChapter, Boolean isLocal, Boolean hasUp, Boolean isTop) {
        this.id = id;
        this.Path = Path;
        this.size = size;
        this.bookId = bookId;
        this.cover = cover;
        this.title = title;
        this.lastChapter = lastChapter;
        this.isLocal = isLocal;
        this.hasUp = hasUp;
        this.isTop = isTop;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return Path;
    }

    public void setPath(String Path) {
        this.Path = Path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getBookId() {
        return bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    public String getLastChapter() {
        return lastChapter;
    }

    public void setLastChapter(String lastChapter) {
        this.lastChapter = lastChapter;
    }

    public Boolean getIsLocal() {
        return isLocal;
    }

    public void setIsLocal(Boolean isLocal) {
        this.isLocal = isLocal;
    }

    public Boolean getHasUp() {
        return hasUp;
    }

    public void setHasUp(Boolean hasUp) {
        this.hasUp = hasUp;
    }

    public Boolean getIsTop() {
        return isTop;
    }

    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    public boolean isSelect() {
        return isSelect;
    }

    public void setSelect(boolean select) {
        isSelect = select;
    }

    public int getChaptersCount() {
        return chaptersCount;
    }

    public void setChaptersCount(int chaptersCount) {
        this.chaptersCount = chaptersCount;
    }

    @Override
    public String toString() {
        return "LocalAndRecomendBook{" +
                "id=" + id +
                ", Path='" + Path + '\'' +
                ", size=" + size +
                ", bookId='" + bookId + '\'' +
                ", cover='" + cover + '\'' +
                ", title='" + title + '\'' +
                ", lastChapter='" + lastChapter + '\'' +
                ", isLocal=" + isLocal +
                ", hasUp=" + hasUp +
                ", isTop=" + isTop +
                ", isSelect=" + isSelect +
                ", chaptersCount=" + chaptersCount +
                '}';
    }
}
